version: "3.9"

services:
  postgresql-1:
    image: postgres:13
    container_name: pg-1
    environment:
      POSTGRES_PASSWORD: pg1
      POSTGRES_USER: pg1user
      POSTGRES_DB: pg1
    ports:
      - "15432:5432"
    volumes:
      - type: bind
        source: ./pg1-init
        target: /docker-entrypoint-initdb.d
  postgresql-2:
    image: postgres:13
    container_name: pg-2
    environment:
      POSTGRES_PASSWORD: pg2
      POSTGRES_USER: pg2user
      POSTGRES_DB: pg2
    ports:
      - "25432:5432"
    volumes:
      - type: bind
        source: ./pg2-init
        target: /docker-entrypoint-initdb.d
